# Generated by Django 2.1.5 on 2019-02-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190213_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
    ]
