# Generated by Django 2.1.5 on 2019-02-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190213_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='filtered_image',
            field=models.ImageField(default=None, upload_to='%Y/%m/%d/filtered'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='%Y/%m/%d/orig'),
        ),
    ]
