# Generated by Django 2.1.5 on 2019-02-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190213_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
    ]
